"""empty message

Revision ID: 0afe8fa24765
Revises: 
Create Date: 2022-03-03 23:57:44.429658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afe8fa24765'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bondprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bondprice_price'), 'bondprice', ['price'], unique=True)
    op.create_table('drawlocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawlocation_location'), 'drawlocation', ['location'], unique=True)
    op.create_table('drawnumber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_role'), 'role', ['role'], unique=True)
    op.create_table('bond',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_price_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['bond_price_id'], ['bondprice.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bond_price_id', 'serial', name='unique_bond')
    )
    op.create_table('bondprize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_price_id', sa.Integer(), nullable=False),
    sa.Column('prize', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bond_price_id'], ['bondprice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bond_price_id', 'prize', name='unique_bond_prize')
    )
    op.create_index(op.f('ix_bondprize_prize'), 'bondprize', ['prize'], unique=True)
    op.create_table('drawdate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bond_price_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bond_price_id'], ['bondprice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'bond_price_id', name='unique_drawdate')
    )
    op.create_index(op.f('ix_drawdate_date'), 'drawdate', ['date'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('body', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_name'), 'notifications', ['name'], unique=False)
    op.create_index(op.f('ix_notifications_timestamp'), 'notifications', ['timestamp'], unique=False)
    op.create_table('updatedlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('bond_price_id', sa.Integer(), nullable=False),
    sa.Column('uploaded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bond_price_id'], ['bondprice.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['date_id'], ['drawdate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_id', 'bond_price_id', name='unique_bond_list')
    )
    op.create_table('userbond',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bond.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'bond_id')
    )
    op.create_table('winningbond',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bond_id', sa.Integer(), nullable=False),
    sa.Column('bond_prize_id', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('draw_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bond.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bond_prize_id'], ['bondprize.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['date_id'], ['drawdate.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['draw_id'], ['drawnumber.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['drawlocation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bond_id', 'bond_prize_id', 'date_id', name='unique_bond_winner')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winningbond')
    op.drop_table('userbond')
    op.drop_table('updatedlist')
    op.drop_index(op.f('ix_notifications_timestamp'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_name'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_drawdate_date'), table_name='drawdate')
    op.drop_table('drawdate')
    op.drop_index(op.f('ix_bondprize_prize'), table_name='bondprize')
    op.drop_table('bondprize')
    op.drop_table('bond')
    op.drop_index(op.f('ix_role_role'), table_name='role')
    op.drop_table('role')
    op.drop_table('drawnumber')
    op.drop_index(op.f('ix_drawlocation_location'), table_name='drawlocation')
    op.drop_table('drawlocation')
    op.drop_index(op.f('ix_bondprice_price'), table_name='bondprice')
    op.drop_table('bondprice')
    # ### end Alembic commands ###
